# -*- coding: utf-8 -*-
"""preprocess_price_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16J9zmt3-RoXQayqBDx_fYXfb2djVeU4A
"""

import pandas as pd

def preprocess_price_data(file_path):
    df = pd.read_csv(file_path)

    # Ensure Datetime is parsed
    df['Datetime'] = pd.to_datetime(df['Datetime'])

    # Extract date only
    df['date'] = df['Datetime'].dt.date

    # Group by date and take last 'Close' price of each day
    daily_close = df.groupby('date')['Close'].last().reset_index()

    # Calculate daily returns
    daily_close['price_change'] = daily_close['Close'].pct_change()

    return daily_close[['date', 'price_change']]

# Example
price1_df = preprocess_price_data('data/prices/BTC-USD_price.csv')
price1_df.to_csv('data/BTC-USD_processedprice.csv', index=False)

price2_df = preprocess_price_data('data/prices/ETH-USD_price.csv')
price2_df.to_csv('data/ETH-USD_processedprice.csv', index=False)

price3_df = preprocess_price_data('data/prices/SOL-USD_price.csv')
price3_df.to_csv('data/SOL-USD_processedprice.csv', index=False)

price4_df = preprocess_price_data('data/prices/AAPL_price.csv')
price4_df.to_csv('data/AAPL_processedprice.csv', index=False)

price5_df = preprocess_price_data('data/prices/TSLA_price.csv')
price5_df.to_csv('data/TSLA_processedprice.csv', index=False)