# -*- coding: utf-8 -*-
"""news_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjfbjnzbWTF4H5eVh_ZN7cMvrM3fN22r

<a href="https://colab.research.google.com/github/atharvkaushik1910/GoQuant--Sentiment-Analysis/blob/main/news_ingest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

# News Headlines (via NewsAPI)

from newsapi import NewsApiClient
import pandas as pd

def fetch_news_data(query, pages=1, page_size=20):
    newsapi = NewsApiClient(api_key='ef6d3ee4ee584cbaab14a9513270f3ef')

    all_articles = []

    for page in range(1, pages + 1):
        response = newsapi.get_everything(
            q=query,
            language='en',
            sort_by='relevancy',
            page=page,
            page_size=page_size
        )
        for article in response['articles']:
            all_articles.append([article['title'], article['description'], article['url'], article['publishedAt']])

    df = pd.DataFrame(all_articles, columns=['Title', 'Description', 'URL', 'PublishedAt'])
    df.to_csv('data/news_headlines.csv', index=False)
    print(f"Saved {len(df)} news articles to data/news_headlines.csv")

    return df