# -*- coding: utf-8 -*-
"""news_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/atharvkaushik1910/GoQuant--Sentiment-Analysis/blob/main/news_ingest.ipynb
"""

# News Headlines (via NewsAPI)
!pip install pandas snscrape praw newsapi-python yfinance

from newsapi import NewsApiClient

newsapi = NewsApiClient(api_key='ef6d3ee4ee584cbaab14a9513270f3ef')

top_headlines = newsapi.get_everything(q='bitcoin OR crypto',
                                       language='en',
                                       sort_by='relevancy',
                                       page_size=10)

news_list = []
for article in top_headlines['articles']:
    news_list.append([article['title'], article['description']])

df_news = pd.DataFrame(news_list, columns=['Title', 'Description'])
print(df_news.head())