# -*- coding: utf-8 -*-
"""prices_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMmiTyITAY0LXZWuOQISLj68FswwWODU

<a href="https://colab.research.google.com/github/atharvkaushik1910/GoQuant--Sentiment-Analysis/blob/main/prices_ingest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

# Stock & Crypto Prices (via yFinance)
import yfinance as yf
import pandas as pd

def fetch_prices(tickers):
    for ticker in tickers:
        data = yf.Ticker(ticker)
        df = data.history(period="1d", interval="1h")
        df.reset_index(inplace=True)
        df.to_csv(f"data/prices/{ticker}_price.csv", index=False)
        print(f"Saved {ticker} price data to data/prices/{ticker}_price.csv")