# -*- coding: utf-8 -*-
"""prices_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/atharvkaushik1910/GoQuant--Sentiment-Analysis/blob/main/prices_ingest.ipynb
"""

# Stock & Crypto Prices (via yFinance)
!pip install pandas snscrape praw newsapi-python yfinance

import yfinance as yf

btc = yf.Ticker("BTC-USD")
btc_history = btc.history(period="1d", interval="1h")
print(btc_history.head())