# -*- coding: utf-8 -*-
"""reddit_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/atharvkaushik1910/GoQuant--Sentiment-Analysis/blob/main/reddit_ingest.ipynb
"""

!pip install pandas snscrape praw newsapi-python yfinance

import praw

reddit = praw.Reddit(client_id='n8_Bmi8dUSVm1bhwkLpjfA',
                     client_secret='BvDzQQ8KKnGudFac-luVSvHHWVjLig',
                     user_agent='GoQuantSentimentApp')

subreddit = reddit.subreddit('CryptoCurrency')

posts = []
for post in subreddit.hot(limit=100):
    posts.append([post.title, post.selftext, post.score])

df_reddit = pd.DataFrame(posts, columns=['Title', 'Text', 'Score'])
print(df_reddit.head())