# -*- coding: utf-8 -*-
"""twitter_ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/atharvkaushik1910/GoQuant--Sentiment-Analysis/blob/main/twitter_ingest.ipynb
"""

!pip install tweepy pandas

import tweepy
import pandas as pd

bearer_token = 'AAAAAAAAAAAAAAAAAAAAAMpO3AEAAAAAl%2BGUdnDjPwJzXSsZ80qLGpW3jBc%3DGPoIwrnmmqRn09xNmIlU3mYmHqBLJWK5A7NqfDoTPjxY4y9Dsf'

client = tweepy.Client(bearer_token=bearer_token)

def fetch_tweets_via_api(query, max_results=100):
    tweets = client.search_recent_tweets(query=query, max_results=max_results, tweet_fields=['created_at', 'lang', 'author_id', 'text'])

    data = []
    for tweet in tweets.data:
        data.append([tweet.id, tweet.text, tweet.created_at, tweet.lang, tweet.author_id])

    df = pd.DataFrame(data, columns=['TweetID', 'Text', 'CreatedAt', 'Language', 'AuthorID'])
    df.to_csv('tweets_api.csv', index=False)
    return df

query = "bitcoin OR ethereum OR crypto lang:en"
df_api_tweets = fetch_tweets_via_api(query, max_results=100)
print(df_api_tweets.head())