# -*- coding: utf-8 -*-
"""aggregate_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVoVThzmMdsuqLyK5agqTp37lKb4QTdd
"""

# analysis/aggregate_sentiment.py

import pandas as pd

def load_sentiments():
    tweets = pd.read_csv('data/tweets_sentiment.csv')
    reddit = pd.read_csv('data/reddit_sentiment.csv')
    news = pd.read_csv('data/news_sentiment.csv')

    all_data = pd.concat([tweets[['compound']], reddit[['compound']], news[['compound']]], ignore_index=True)
    return all_data

def calculate_index():
    all_sentiments = load_sentiments()
    # Average of all compound scores
    index_value = all_sentiments['compound'].mean()

    print(f"Fear & Greed Index (approx): {index_value:.2f}")
    if index_value > 0.2:
        print("Market is Greedy 🚀 (Consider Buying)")
    elif index_value < -0.2:
        print("Market is Fearful 😨 (Consider Selling)")
    else:
        print("Market is Neutral 🤝")

if __name__ == "__main__":
    calculate_index()