# -*- coding: utf-8 -*-
"""analyze_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nvk_nFZ0v9fxAw3D9B1m2Zrt4ieCq9y2
"""

# analysis/analyze_news.py

import pandas as pd
from sentiment import finbert_sentiment

# Load Tweets
df = pd.read_csv('data/news_headlines.csv')
df['Description'] = df['Description'].fillna("").astype(str)



# Apply FinBERT sentiment
df_sentiments = df['Description'].apply(finbert_sentiment).apply(pd.Series)

# Merge back to original dataframe
df = pd.concat([df, df_sentiments], axis=1)

df.to_csv('data/news_sentiment.csv', index=False)
print(df.head())