# -*- coding: utf-8 -*-
"""analyze_reddit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5t--AcZrEKcjvSoF_ATRleBth9b5DX3
"""

# analysis/analyze_tweets.py

import pandas as pd
from sentiment import finbert_sentiment

# Load Tweets
df = pd.read_csv('data/reddit_posts.csv')
df['Text'] = df['Text'].fillna("").astype(str)



# Apply FinBERT sentiment
df_sentiments = df['Text'].apply(finbert_sentiment).apply(pd.Series)

# Merge back to original dataframe
df = pd.concat([df, df_sentiments], axis=1)

df.to_csv('data/reddit_sentiment.csv', index=False)
print(df.head())