# -*- coding: utf-8 -*-
"""analyze_tweets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbQZify3mqv1tLrwTAC14spE6gH-mUa7
"""

# analysis/analyze_tweets.py

import pandas as pd
from sentiment import finbert_sentiment

# Load Tweets
df = pd.read_csv('data/tweets_api.csv')

# Apply FinBERT sentiment
df_sentiments = df['Text'].apply(finbert_sentiment).apply(pd.Series)

# Merge back to original dataframe
df = pd.concat([df, df_sentiments], axis=1)

df.to_csv('data/tweets_sentiment.csv', index=False)
print(df.head())