# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRUOPdMLVVAlLbisWVI3VAqHwRWyDNpD
"""

# analysis/sentiment.py

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd

# Load FinBERT model + tokenizer
tokenizer = AutoTokenizer.from_pretrained("yiyanghkust/finbert-tone")
model = AutoModelForSequenceClassification.from_pretrained("yiyanghkust/finbert-tone")

def finbert_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    outputs = model(**inputs)
    scores = torch.nn.functional.softmax(outputs.logits, dim=1)
    negative, neutral, positive = scores[0]
    # Compound sentiment: positive - negative
    compound_score = positive.item() - negative.item()

    return {
        'positive': positive.item(),
        'neutral': neutral.item(),
        'negative': negative.item(),
        'compound': compound_score
    }